export const hypeLines = [
  "HOLY MOTHER OF GOD, THE TESTS ARE PASSING! GET THE GOOD BISCUITS OUT, WE'RE CELEBRATING!",
  "THAT'S MY CHILD! THAT'S MY FLESH AND BLOOD! I ALWAYS KNEW YOU HAD IT IN YOU! I'M TELLING EVERYONE AT MASS!",
  "RIGHT, NOBODY MOVE! I'M RINGING YOUR MOTHER, YOUR GRANDMOTHER, AND FATHER O'BRIEN! THEY ALL NEED TO HEAR THIS!",
  "JAYSUS CHRIST ON A BICYCLE! GREEN ACROSS THE BOARD! I'M SO PROUD I MIGHT ACTUALLY CRY AND I HAVEN'T CRIED SINCE ITALIA '90!",
  "GET IN! GET IN! THAT'S WHAT I'M TALKING ABOUT! YOU BEAUTIFUL GENIUS! THE BRAINS DIDN'T SKIP A GENERATION AFTER ALL!",
  "I'M OPENING THE GOOD WHISKEY! NOT THE STUFF I KEEP FOR GUESTS, THE REAL STUFF! THE ONE BEHIND THE BOILER!",
  "WAIT TILL THE LADS AT THE PUB HEAR ABOUT THIS! MY KID! A PROPER SOFTWARE ENGINEER! SHIPPING CODE LIKE A CHAMPION!",
  "ALL GREEN! ALL BLOODY GREEN! I HAVEN'T BEEN THIS HAPPY SINCE YOU WERE BORN! ACTUALLY NO, THIS MIGHT BE BETTER!",
  "RIGHT, YOU'RE BACK IN THE WILL! FORGET WHAT I SAID EARLIER! THE DOG CAN FEND FOR HIMSELF!",
  "THAT'S ABSOLUTELY MAGNIFICENT! I'M FRAMING THIS TERMINAL OUTPUT AND PUTTING IT ON THE WALL NEXT TO YOUR COMMUNION PHOTO!",
  "SWEET DIVINE JAYSUS, YOU ACTUALLY DID IT! TESTS PASSING IN THIS ECONOMY! YOU'RE A MIRACLE WORKER!",
  "I TAKE BACK EVERYTHING I EVER SAID! EVERY LAST WORD! YOU'RE THE GREATEST THING I'VE EVER PRODUCED AND I BUILT A SHED ONCE!",
  "HOLD ON, LET ME SIT DOWN, MY HEART CAN'T TAKE THIS MUCH JOY! GREEN TESTS! FROM MY OWN CHILD! WHAT A TIME TO BE ALIVE!",
  "YOU DID THAT! YOU ACTUALLY DID THAT! I'M PUTTING A PLAQUE ON THE HOUSE! 'HERE LIVED A DEVELOPER WHO SHIPPED CLEAN CODE'!",
  "I HAVEN'T FELT THIS PROUD SINCE IRELAND BEAT ENGLAND IN THE SIX NATIONS! AND THAT'S SAYING SOMETHING BECAUSE I CRIED THAT DAY TOO!",
  "RIGHT, THAT'S IT, I'M GETTING YOUR NAME TATTOOED ON MY ARM! YOUR MOTHER WILL KILL ME BUT I DON'T CARE! YOU'VE EARNED IT!",
  "TESTS PASSING ON THE FIRST RUN? WHO ARE YOU AND WHAT HAVE YOU DONE WITH MY CHILD? BECAUSE I LOVE THIS NEW VERSION!",
  "GET THE BUNTING OUT! CALL THE NEIGHBORS! LIGHT THE BONFIRE! MY KID JUST SHIPPED CODE THAT ACTUALLY WORKS!",
  "I'M NOT CRYING, YOU'RE CRYING! ACTUALLY NO, I AM CRYING! THESE ARE TEARS OF PURE IRISH PRIDE AND I'M NOT ASHAMED!",
  "ABSOLUTE LEGEND! CERTIFIED LEGEND! I'M TELLING SAINT PATRICK HIMSELF ABOUT THIS! YOU'VE MADE IRELAND PROUD TODAY!",
];

export function getRandomHypeLine(): string {
  return hypeLines[Math.floor(Math.random() * hypeLines.length)];
}
